/** Open Graph / Twitter card image (generated by `app/opengraph-image.tsx`). */
export const socialPreviewImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Telemetry Tracker — Observability for teams that ship",
} as const;
